### ISSUE TITLE
how to use the role

### ISSUE THREAD

**Issue by ghost** [wolffaxn/ansible-role-gradle#1]
hi, thanks for sharing this.

I think the gradle installation was successful but I have some trouble using the installed gradle.

GRADLE_HOME is not set

``` bash
$ echo $GRADLE_HOME

```

``` bash
$  /opt/gradle-3.2.1/bin/gradle --version

------------------------------------------------------------
Gradle 3.2.1
------------------------------------------------------------

Build time:   2016-11-22 15:19:54 UTC
Revision:     83b485b914fd4f335ad0e66af9d14aad458d2cc5

Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.7.0_131 (Oracle Corporation 24.131-b00)
OS:           Linux 4.9.27-moby amd64
```

here is what I try to do:

``` yaml
---
- hosts: jenkins

  tasks:
    - name: Test groovy job.
      command: >
        gradle test
      args:
        chdir: /etc/ansible/jobs

  roles:
    - ansible-role-gradle
    - geerlingguy.java
```

What is the best way to refer to the installed gradle command?
I think an  example would be great

Best,
Mark
